apiVersion: v1
kind: Service
metadata:
  labels:
    app: centralog
  name: centralog

spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    app: centralog
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: centralog
  name: centralog

spec:
  replicas: 1
  selector:
    matchLabels:
      app: centralog
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: centralog
    spec:
      priorityClassName: high-priority
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/pivotstudio/centralog:{{.build_tag}}
        name: centralog
        command: ["/app","-c","mongodb://mongodb.default.svc.cluster.local:27017"]
        ports:
          - containerPort: 8001
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests: 
            cpu: 100m
            memory: 100Mi
            

      restartPolicy: Always
status: {}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: centralog

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: centralog
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60


