name: docker-ci

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build Backend and push
        id: docker_backend_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/pivotstudio/centralog:latest
      - name: Backend Image digest
        run: echo ${{ steps.docker_backend_build.outputs.digest }}
      # - name: deploy to cluster
      #   uses: steebchen/kubectl@v2.0.0
      #   with: # defaults to latest kubectl binary version
      #     config: ${{ secrets.KUBE_CONFIG_DATA }}
      #     command:  set image deployment/hole-backend hole-backend=registry.cn-hangzhou.aliyuncs.com/pivotstudio/hole-backend:${{ env.RELEASE_VERSION }} -n hole --record
      # - name: verify deployment
      #   uses: steebchen/kubectl@v2.0.0
      #   with:
      #     config: ${{ secrets.KUBE_CONFIG_DATA }}
      #     version: v1.21.0 # specify kubectl binary version explicitly
      #     command: rollout status deployment/hole-backend -n hole